# Codecov Configuration
# Docs: https://docs.codecov.com/docs/codecov-yaml

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        target: auto
        threshold: 1%
        if_ci_failed: error
        informational: false

    patch:
      default:
        target: 80%
        threshold: 5%
        if_ci_failed: error
        informational: false

comment:
  layout: "diff,flags,files,footer"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true
  # 防止多个 job 上传时重复评论
  after_n_builds: 1

ignore:
  - "scripts/"
  - "tests/"
  - "**/test_*.py"
  - "**/__init__.py"
  - "**/__main__.py"
  - ".venv/"
  - "*.egg-info/"
  - "build/"
  - "dist/"

github_checks:
  annotations: true
